<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Cookie;
use Illuminate\Support\Facades\Session;


class AuthController extends Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub

    }

    public function indexRegister()
    {
        if($this->checkLogin()==true)
        {
            return redirect('/');
        }
        return view('auth/register');
    }

    public function indexLogin()
    {
        if($this->checkLogin()==true)
        {
            return redirect('/');
        }
        return view('auth/login');
    }

    public function insert(Request $request)
    {

        if($this->checkLogin()==true)
        {
            return redirect('/');
        }
//        $request->replace(['foo' => 'bar']);
//        dd($request->name);

        if($request->password != $request->password2)
        {
            $data = [
                'retypepassword' => 'Please write the same password'
            ];
            return view('auth/register',compact('data'));
        }

        $user = $this->guzzlePost($request->all(),'users/add');


        if(!empty($user['nametaken']))
        {
            return view('auth/register',compact('user'));
        }else if(!empty($user['emailtaken']))
        {
            return view('auth/register',compact('user'));
        }


        $this->createSession($this->jwtDecode($user));

        return redirect('/');
    }

    public function login(Request $request)
    {
        if($this->checkLogin()==true)
        {
            return redirect('/');
        }

        $user =  $this->guzzleGet('users/login/'.$request->name);
        dd($user);
        $this->createSession($this->jwtDecode($user));

        return redirect('/');
    }

    public function logout()
    {
        if($this->checkLogin()==false)
        {
            return redirect('/');
        }
        $this->sessionClear();
        return redirect('/');
    }


}
