<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use GuzzleHttp\Client;
use Illuminate\Support\Facades\Session;

class HomeController extends Controller
{
    public function __construct()
    {
        parent::__construct(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        $client  = new Client([
//            'headers' => ['content-type' => 'application/json' , 'Accept' => 'application/json']
//    ]);
//        $response = $client->request('GET','OnlineStoreApi/api/v1/posts/index');
//
//        $client = new Client(
////            [
////            // Base URI is used with relative requests
////            'base_uri' => 'OnlineStoreApi',
////            // You can set any number of default request options.
////            'timeout'  => 2.0,
////            ]
//        );

//        $categories = $client->get('api/api/v1/categories/index');
//
//        $subcategories = $client->get('api/api/v1/subcategories/index');
//
//        $home = $client->get('api/api/v1/home/index');
////        dd($home);
//        dd(Session::get('name'));

        $data['categories'] = $this->guzzleGet('categories/index');
        $data['subcategories'] = $this->guzzleGet('subcategories/index');
        $data['homeproduces'] = $this->guzzleGet('home/index');
        return view('home' , compact('data'));
    }
}
